import {readIdoceo,writeIdoceo,idoceoRows} from './idoceo.mjs';
import {createFileBytes,restoreFileBytes,FILE_NAME,FILE_TYPE} from './file-store.mjs';
import {empty,bindQR,mark,scan,validate,localDate,dailySession,startDaily,finishDaily,reopenDaily,exportDailyCSV,parseCSV,importRosterFile,groupFromFilename,linkAndScan} from './core.mjs';
const $=id=>document.getElementById(id);let db,data=empty(),groupId='',day=localDate(),busy=false,stream=null,generation=0,pendingQR='',lastScan='',lastAt=0,noticeTimer,sharing=false;
function notice(text,error=false){clearTimeout(noticeTimer);$('message').textContent=text;$('message').className=error?'error':'';$('message').hidden=false;if($('cameraDialog').open)$('cameraMessage').textContent=text;if($('linkDialog').open&&error)$('linkDialog').querySelector('.muted').textContent=text;if(!error)noticeTimer=setTimeout(()=>{$('message').hidden=true;},4500);}
const safe=fn=>async e=>{try{await fn(e);}catch(err){notice(err.message||'No se pudo completar la acción.',true);}};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('aula-asistencia',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Cierra otras ventanas de la app y vuelve a abrirla.'));});}
function read(){return new Promise((resolve,reject)=>{const t=db.transaction('state'),r=t.objectStore('state').get('main');r.onsuccess=()=>resolve(r.result||empty());r.onerror=()=>reject(r.error);});}
function write(next){return new Promise((resolve,reject)=>{let conflict=false;const t=db.transaction('state','readwrite'),s=t.objectStore('state'),r=s.get('main');r.onsuccess=()=>{if((r.result?.revision||0)!==data.revision){conflict=true;t.abort();return;}next.revision=data.revision+1;s.put(next,'main');};t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(Error(conflict?'Hay cambios en otra ventana. Recarga la app antes de continuar.':'No se guardó: almacenamiento no disponible. Guarda un respaldo y libera espacio.'));});}
async function change(fn){if(!db)throw Error('Almacenamiento no disponible.');if(busy)throw Error('Espera a que termine el guardado.');busy=true;try{const next=structuredClone(data);const result=fn(next);validate(next);await write(next);data=next;render();return result;}finally{busy=false;}}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function options(select,items,value){select.replaceChildren();for(const [id,label]of items){const option=element('option',label);option.value=id;select.append(option);}select.value=value;}
function session(){return dailySession(data,groupId,day);}
const arrived=s=>Object.values(s?.records||{}).filter(r=>['presente','retraso'].includes(r.status)).length;
function render(){
 if(!data.groups.some(g=>g.id===groupId))groupId=data.groups[0]?.id||'';
 $('welcome').hidden=Boolean(data.students.length);$('workspace').hidden=!data.students.length;
 options($('group'),data.groups.map(g=>[g.id,g.name]),groupId);
 $('dateLabel').textContent=new Date(day+'T12:00:00').toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'});
 const s=session(),students=data.students.filter(s=>s.groupId===groupId);
 $('dayStatus').textContent=s?.closed?'Hoy · Ya registrada':s?'Hoy · En curso':'Hoy';
 $('count').textContent=s?`${arrived(s)} de ${s.roster.length}`:`${students.length} alumnos`;
 $('startDay').textContent=s?'Continuar escaneando':'Tomar asistencia';$('startDay').hidden=Boolean(s?.closed);$('startDay').disabled=!students.length||busy&&sharing;
 $('finishDay').hidden=!s||s.closed;$('absences').hidden=!s?.closed;$('manualList').hidden=!s;
 const absent=s?.roster.filter(r=>s.records[r.id]?.status==='ausente')||[];$('absentCount').textContent=absent.length;$('noAbsences').hidden=absent.length>0;$('absentList').replaceChildren();for(const r of absent){const li=element('li',r.name);if(r.code)li.append(element('small',r.code));$('absentList').append(li);}
 $('attendanceList').replaceChildren();for(const r of s?.roster||[]){const row=element('div',undefined,'person'),name=element('div'),status=element('select');name.append(element('b',r.name),element('small',s.records[r.id]?.time?new Date(s.records[r.id].time).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}):r.code||''));status.setAttribute('aria-label',`Asistencia de ${r.name}`);options(status,[['pendiente','Pendiente'],['presente','✔️ Presente'],['ausente','❌ Falta'],['retraso','⌛️ Retraso'],['justificado','Justificado']],s.records[r.id]?.status||'pendiente');status.onchange=safe(async()=>{const value=status.value;try{await change(d=>{if(s.closed)reopenDaily(d,s.id);mark(d,s.id,r.id,value);if(s.closed&&value!=='pendiente')finishDaily(d,s.id);});$('saveStatus').textContent='Cambios nuevos. Guarda el archivo.';}catch(e){render();throw e;}});row.append(name,status);$('attendanceList').append(row);}
 $('historyTable').replaceChildren();if(!data.idoceo&&!data.sessions.some(s=>s.groupId===groupId))$('historyTable').append(element('p','Aún no hay registros.','muted'));else{const rows=data.idoceo?idoceoRows(data):parseCSV(exportDailyCSV(data,groupId)),table=element('table');rows.forEach((row,i)=>{const tr=element('tr');row.forEach((v,j)=>{if(j!==0&&j!==2)tr.append(element(i?'td':'th',v));});table.append(tr);});$('historyTable').append(table);}
 $('studentList').replaceChildren();for(const student of students){const row=element('div',undefined,'person'),label=element('div');label.append(element('b',student.name),element('small',student.qr?'QR asociado':'Sin QR'));const edit=element('button','Corregir','text-button');edit.onclick=safe(async()=>{const name=prompt('Nombre del alumno:',student.name);if(name===null)return;if(!name.trim())throw Error('El nombre es obligatorio.');const qr=prompt('Contenido del QR (vacío para volver a asociar al escanear):',student.qr);if(qr===null)return;await change(d=>{const a=d.students.find(s=>s.id===student.id);a.name=name.trim();if(qr)bindQR(d,a.id,qr);else a.qr='';});notice('Alumno actualizado.');});row.append(label,edit);$('studentList').append(row);}
 $('saveMenu').disabled=!data.students.length;$('exportMatrix').hidden=Boolean(data.idoceo);
}
function refreshDay(){const today=localDate();if(today!==day){stopCamera();day=today;render();notice('Ya puedes iniciar la asistencia de hoy.');}}
$('group').onchange=()=>{stopCamera();groupId=$('group').value;$('saveStatus').textContent='';render();};
$('menuButton').onclick=()=>$('menuDialog').showModal();$('closeMenu').onclick=()=>$('menuDialog').close();
function pickFile(){$('menuDialog').close();$('fileInput').click();}
$('openFile').onclick=pickFile;$('changeFile').onclick=pickFile;
$('fileInput').onchange=safe(async()=>{const f=$('fileInput').files[0];if(!f)return;stopCamera();try{
 if(f.size>20e6)throw Error('El archivo supera 20 MB.');
 if(/\.(csv|tsv)$/i.test(f.name)){const text=await f.text(),name=groupFromFilename(f.name);await change(d=>importRosterFile(d,text,f.name));groupId=data.groups.find(g=>g.name.toLowerCase()===name.toLowerCase())?.id||groupId;render();}
 else{const bytes=await f.arrayBuffer();let restored;
 if(/\.json$/i.test(f.name))restored=validate(JSON.parse(new TextDecoder().decode(bytes)));
 else {const book=XLSX.read(bytes,{type:'array'});restored=book.Sheets.Datos_app?restoreFileBytes(bytes):readIdoceo(bytes,f.name);}
 if(data.sessions.some(s=>!s.closed)&&!confirm('Hay una toma en curso. ¿Descartarla y abrir este archivo?'))return;
 if(!data.sessions.some(s=>!s.closed)&&data.sessions.length&&JSON.stringify(data.sessions)!==JSON.stringify(restored.sessions)&&!confirm('Se abrirá el historial del archivo seleccionado. Comprueba que sea tu última copia. ¿Continuar?'))return;
 await change(d=>{d.groups=restored.groups;d.students=restored.students;d.sessions=restored.sessions;if(restored.idoceo)d.idoceo=restored.idoceo;else delete d.idoceo;});groupId=data.groups[0]?.id;day=localDate();render();}
 if(session()?.closed){notice('La asistencia de hoy ya está registrada. Pulsa Añadir a alguien para completarla.');}else await begin();
 }finally{$('fileInput').value='';}});

async function begin(){refreshDay();const s=session();if(!s)await change(d=>startDaily(d,groupId,day));else if(s.closed)await change(d=>reopenDaily(d,s.id));await startCamera();}
$('startDay').onclick=safe(begin);$('resumeDay').onclick=safe(begin);
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=element('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function saveFile(){
 if(sharing)return;const filename=data.idoceo?.filename||FILE_NAME;const file=new File([data.idoceo?writeIdoceo(data):createFileBytes(data)],filename,{type:FILE_TYPE});sharing=true;$('saveFile').disabled=true;$('saveMenu').disabled=true;
 try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file]});$('saveStatus').textContent='Comprueba tu archivo en Archivos.';}else{download(file,filename,FILE_TYPE);$('saveStatus').textContent='Archivo descargado. Puedes guardarlo en Archivos.';}}
 catch(e){$('saveStatus').textContent=e.name==='AbortError'?'Guardado cancelado. Puedes guardar aquí.':'Pulsa Guardar archivo para abrir el guardado del teléfono.';}
 finally{sharing=false;$('saveFile').disabled=false;$('saveMenu').disabled=false;}
}
async function finish(){const s=session();if(!s||s.closed)return;stopCamera();clearTimeout(noticeTimer);$('message').hidden=true;await change(d=>finishDaily(d,s.id));$('manualList').open=false;$('saveStatus').textContent='';await saveFile();}
$('finishDay').onclick=safe(finish);$('finishCamera').onclick=safe(finish);$('saveFile').onclick=safe(saveFile);$('saveMenu').onclick=safe(()=>{$('menuDialog').close();return saveFile();});
$('exportMatrix').onclick=()=>download(exportDailyCSV(data,groupId),`asistencia-${day}.csv`,'text/csv;charset=utf-8');
function showLink(qr){pendingQR=qr;$('findStudent').value='';$('linkDialog').querySelector('.muted').textContent='Solo tendrás que elegirlo esta vez.';renderLinks();$('linkDialog').showModal();}
function renderLinks(){const s=session(),filter=$('findStudent').value.toLocaleLowerCase('es');$('linkStudents').replaceChildren();for(const r of s?.roster||[]){const student=data.students.find(x=>x.id===r.id);if(student.qr||!`${r.name} ${r.code}`.toLocaleLowerCase('es').includes(filter))continue;const button=element('button',r.name,'student-choice');if(r.code)button.append(element('small',r.code));button.onclick=safe(async()=>{if(day!==localDate()){refreshDay();throw Error('Cambió el día. Inicia la asistencia de hoy.');}const qr=pendingQR;if(!qr)return;const result=await change(d=>linkAndScan(d,s.id,r.id,qr));pendingQR='';$('linkDialog').close();confirmScan(result);});$('linkStudents').append(button);}if(!$('linkStudents').children.length)$('linkStudents').append(element('p','No hay alumnos sin QR que coincidan. Puedes corregir un QR desde Archivo.','muted'));}
$('findStudent').oninput=renderLinks;function cancelLink(){pendingQR='';lastAt=Date.now();$('linkDialog').close();}$('cancelLink').onclick=cancelLink;$('linkDialog').addEventListener('cancel',cancelLink);
function confirmScan(result){const text=result.changed?`✔️ ${result.student.name}`:`${result.student.name} · ya registrado`;$('cameraMessage').textContent=text;$('cameraCount').textContent=`${arrived(session())} de ${session().roster.length}`;if(!$('cameraDialog').open)notice(text);}
async function acceptQR(qr){if(day!==localDate()){refreshDay();throw Error('Cambió el día.');}const s=session();if(!s||s.closed)throw Error('Abre la asistencia para registrar.');if(!data.students.some(s=>s.qr===qr)){showLink(qr);return;}confirmScan(await change(d=>scan(d,s.id,qr)));}
$('scanForm').onsubmit=safe(async e=>{e.preventDefault();await acceptQR($('rawQR').value);$('rawQR').value='';});
function stopCamera(){generation++;stream?.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;pendingQR='';if($('linkDialog').open)$('linkDialog').close();if($('cameraDialog').open)$('cameraDialog').close();}
async function startCamera(){stopCamera();if(!isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('La cámara necesita HTTPS. También puedes registrar desde Lista y correcciones.');const current=generation;$('cameraTitle').textContent=data.groups.find(g=>g.id===groupId)?.name||'';$('cameraMessage').textContent='Apunta a una tarjeta.';$('cameraCount').textContent=`${arrived(session())} de ${session().roster.length}`;$('cameraDialog').showModal();try{const result=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});if(current!==generation){result.getTracks().forEach(t=>t.stop());return;}stream=result;$('video').srcObject=stream;await $('video').play();lastScan='';lastAt=0;tick(current);}catch(e){stopCamera();throw Error('No se pudo abrir la cámara. Permite el acceso a la cámara en tu navegador o usa Lista y correcciones.');}}
const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
async function tick(current){if(!stream||current!==generation)return;try{const v=$('video');if(!pendingQR&&v.readyState>=2&&v.videoWidth){const scale=Math.min(1,900/v.videoWidth);canvas.width=Math.round(v.videoWidth*scale);canvas.height=Math.round(v.videoHeight*scale);ctx.drawImage(v,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height),qr=window.jsQR(frame.data,frame.width,frame.height,{inversionAttempts:'attemptBoth'});if(qr&&(qr.data!==lastScan||Date.now()-lastAt>3000)){lastScan=qr.data;lastAt=Date.now();await acceptQR(qr.data);}}}catch(e){$('cameraMessage').textContent=e.message;}if(stream&&current===generation)setTimeout(()=>tick(current),170);}
$('stopCamera').onclick=stopCamera;$('cameraDialog').addEventListener('cancel',stopCamera);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else refreshDay();});window.addEventListener('pagehide',stopCamera);setInterval(refreshDay,30000);
try{db=await openDB();data=validate(await read());render();navigator.storage?.persist?.().catch(()=>{});}catch(e){notice(`No se pudo abrir el registro: ${e.message}`,true);$('openFile').disabled=true;$('startDay').disabled=true;}
if('serviceWorker'in navigator&&isSecureContext){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('offlineStatus').textContent='Lista sin conexión. Prueba abrirla en modo avión antes de clase.';}catch{$('offlineStatus').textContent='Abre la app con internet para preparar el modo sin conexión.';}}else $('offlineStatus').textContent='Necesitas HTTPS para cámara y uso sin conexión.';
